# Generated by Django 6.0.3 on 2026-03-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_author_product_book_format_product_genre_and_more'),
    ]

    operations = [
    ]
